seed: 0
data_parameters:
  data_path: '/home/inspur/zhengchao/datasets'
  # dataset: 'Receipt'
  # dataset: 'helpdesk2017'
  # dataset: 'BPIC2020_PrepaidTravelCost'
  # dataset: 'BPIC2020_InternationalDeclarations'
  # dataset: 'BPIC2020_DomesticDeclarations'
  dataset: 'BPIC2020_RequestForPayment'
  # dataset: 'Sepsis'
  # dataset: 'BPI2015_1'
  valid_ratio: 0.2

model_parameters:
  model_name: 'ESF'
  batch_size: 1024
  num_epochs: 200
  dimension: 64
  hidden_size: 128
  dropout: 0.3
  learning_rate: 0.001
  max_patience_num: 50
  alpha: 0.1
  threhold: 0.5