seed: 0
data_parameters:
  data_path: '/home/inspur/zhengchao/datasets'
  dataset: 'Receipt'
  # dataset: 'BPIC2020_PrepaidTravelCost'
  # dataset: 'BPIC2020_InternationalDeclarations'
  # dataset: 'BPIC2020_DomesticDeclarations'
  # dataset: 'BPIC2020_RequestForPayment'
  valid_ratio: 0.2
  k_fold_num: 3

model_parameters:
  model_name: 'ESF'
  future_window_size: 3
  batch_size: 1024
  num_epochs: 300
  warm_up_epochs: 0
  warm_up_patience_num: 10
  dimension: 64
  hidden_size: 128
  threshold: 0.2
  dropout: 0.5
  learning_rate: 0.001
  max_patience_num: 50
  alpha: 10