seed: 0
data_parameters:
  data_path: '/home/inspur/zhengchao/datasets'
  # dataset: 'Sepsis'
  # dataset: 'Receipt'
  # dataset: 'BPIC2020_PrepaidTravelCost'
  dataset: 'BPIC2020_RequestForPayment'
  valid_ratio: 0.2

model_parameters:
  model_name: 'ESF'
  batch_size: 1024
  num_epochs: 150
  hidden_size_1: 128
  hidden_size_2: 32
  dropout: 0.2
  learning_rate: 0.0001
  max_patience_num: 24
  alpha: 0.5
  threhold: 0.5